app:
    resource: '@AppBundle/Controller/'
    type: annotation

start_page:
    path:     /
    defaults: { _controller: AppBundle:Product:index }

product_list:
    path:     /products
    defaults: { _controller: AppBundle:Product:index }

manufacturing_resource_list:
    path:     /manufacturing_stock
    defaults: { _controller: AppBundle:ManufacturingStock:index }

manufacturing_resource_change:
    path:     /manufacturing_resource_change/{id}
    defaults: { _controller: AppBundle:ManufacturingStock:resourceChange }

flush_db:
    path:     /flush_db
    defaults: { _controller: AppBundle:Debug:flushDb }