app:
    resource: '@AppBundle/Controller/'
    type: annotation

product_list:
    path:     /products
    defaults: { _controller: AppBundle:Product:index }

blog_list:
    path:     /blog
    defaults: { _controller: AppBundle:Blog:index }

blog_show:
    path:     /blog/{slug}
    defaults: { _controller: AppBundle:Blog:show }